### ISSUE TITLE
Previous images get removed whenever adding new images on multiple files choosen type.

### ISSUE THREAD

**Issue by tayeb-khan** [JaxThePrime/vue3-dropzone#1]
Whenever adding new files with the existing selected files it's removing my old files and only keeping the new ones.

**Comment by JaxThePrime** [comment]
Hello my friend the new version is out there!
new prop is added to make the selecting file strategy custom for you just
simply add this

select-file-strategy="merge"

**Comment by tayeb-khan** [comment]
Thanks it works! And if you could make the dropzone funcionality like the jquery, onDrop direct upload to server with progress bar it will make the package much usable.
