### ISSUE TITLE
Basic Functionality issue

### ISSUE THREAD

**Issue by CarlosKVillanueva** [JaxThePrime/vue3-dropzone#15]
Hey @JaxThePrime @frankmichel @dazza-dev , I have a problem with some basic functionality, this is my code

`<script setup>
import { ref } from "vue";
import Vue3Dropzone from "@jaxtheprime/vue3-dropzone";
import "@jaxtheprime/vue3-dropzone/dist/style.css";

const files = ref([]);

function handleFileUploaded(file) {
  console.log(file);
}

function handleError(file, message) {
  console.log(file, message);
}
</script>

<template>
  <Vue3Dropzone
    v-model="files"
    :multiple="true"
    :maxFileSize="10"
    @fileUploaded="handleFileUploaded"
    accept="csv"
    @error="handleError"
  />
</template>

<style>

</style>`

Component renders flawlessly in the browser, and all the UI works as expected, the problem is that I not been able to execute the handleFileUpload method on fileUpload event triggers, Im missing something? FYI, error event works as expected and executes

**Comment by JaxThePrime** [comment]
@CarlosKVillanueva Hello it would help if you provide the template part of the code its probably something about the event you listening for on the component tag

**Comment by CarlosKVillanueva** [comment]
Wrapper
```
<DragAndUpload
        class="drag-and-upload"
        v-model="files"
/>
```


DragAndUplad SFC with Vue3Dropzone, @error and @change works as expected, but not the @fileUploaded
```
<script setup>
import { ref } from "vue";
import Vue3Dropzone from "@jaxtheprime/vue3-dropzone";
import "@jaxtheprime/vue3-dropzone/dist/style.css";

const files = ref([]);
const model = defineModel()

function handleFileUploaded(file) {
  console.log(file);
}

function handleError(file, message) {
  console.log(file, message);
}

function handleChange(files) {
  console.log();
}
</script>

<style> </style>`

<template>
  <Vue3Dropzone
    v-model="model"
    :multiple="true"
    :maxFileSize="10"
    @fileUploaded="handleFileUploaded"
    @error="handleError"
    @change="handleChange"
  />
</template>

<style scoped>

</style><script setup>
import { ref } from "vue";
import Vue3Dropzone from "@jaxtheprime/vue3-dropzone";
import "@jaxtheprime/vue3-dropzone/dist/style.css";

const files = ref([]);
const model = defineModel()

function handleFileUploaded(file) {
  console.log(file);
}

function handleError(file, message) {
  console.log(file, message);
}

function handleChange(files) {
  console.log();
}
</script>

<style> </style>`

<template>
  <Vue3Dropzone
    v-model="model"
    :multiple="true"
    :maxFileSize="10"
    @fileUploaded="handleFileUploaded"
    @error="handleError"
    @change="handleChange"
  />
</template>

<style scoped>

</style>
```

**Comment by JaxThePrime** [comment]
Thanks for sharing @CarlosKVillanueva this functionality is a contribution from @dazza-dev Hope he can help you with it and check if it has any bug.

**Comment by dazza-dev** [comment]
Hello, @CarlosKVillanueva . I've reviewed this, and the event is only emitted when files are uploaded to the server. I'm going to emit this event for local uploads as well."

**Comment by JaxThePrime** [comment]
@dazza-dev Thanks for the effort.
